jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      name: Install gpg secret key
      run: 'cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import

        gpg --pinentry-mode=loopback --passphrase "$GPG_PASSPHRASE" --export-secret-keys
        >$HOME/.gnupg/secring.gpg

        gpg --list-secret-keys --keyid-format LONG

        ls -l $HOME/.gnupg

        '
    - continue-on-error: true
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      name: Publish release
      run: './gradlew --info --stacktrace -Psigning.secretKeyRingFile=$HOME/.gnupg/secring.gpg
        -Psigning.password="$GPG_PASSPHRASE" -P signing.keyId=${{ secrets.GPG_KEY_ID
        }} publish

        '
    - continue-on-error: true
      name: Display next step
      run: 'echo "Now go to https://s01.oss.sonatype.org/index.html#stagingRepositories,
        select the repo, Close it and then Release it"

        '
name: Publish to Maven Central
on:
  repository_dispatch:
    types: trigger-ga___publish-maven-central.yml
